"use client"
import { useEffect, useState } from "react"
import type { LogEvent } from "@/lib/types"
const SHAPES = ["●", "▲", "■", "◆", "★", "+"]
export function MemoryGame({ onEvent, audioGuide }: { onEvent: LogEvent; audioGuide: boolean }) {
  const [level, setLevel] = useState(1); const [ready, setReady] = useState(false); const [preview, setPreview] = useState(3); const [flipped, setFlipped] = useState<number[]>([]); const [matched, setMatched] = useState<number[]>([])
  const pairs = Math.min(2 + level, 6); const cols = pairs <= 2 ? 2 : pairs <= 3 ? 3 : 4
  const [deck, setDeck] = useState<string[]>(() => [...Array.from({ length: pairs }, (_, i) => SHAPES[i]), ...Array.from({ length: pairs }, (_, i) => SHAPES[i])].sort(() => Math.random() - 0.5))
  useEffect(() => { if (!ready && preview > 0) { const t = setTimeout(() => setPreview((v) => v - 1), 1000); return () => clearTimeout(t) } }, [preview, ready])
  useEffect(() => { if (audioGuide && typeof window !== "undefined" && "speechSynthesis" in window) window.speechSynthesis.speak(new SpeechSynthesisUtterance("Ingat bentuk kartu, lalu cari pasangan yang sama.")) }, [audioGuide])
  const choose = (i: number) => { if (!ready || flipped.includes(i) || matched.includes(i) || flipped.length === 2) return; const next = [...flipped, i]; setFlipped(next); if (next.length === 2) { const ok = deck[next[0]] === deck[next[1]]; onEvent({ type: ok ? "memory_match" : "memory_mismatch", game: "memory", timestamp: performance.timeOrigin + performance.now(), level, error: ok ? undefined : "mismatch" }); setTimeout(() => { if (ok) { const all = [...matched, ...next]; setMatched(all); if (all.length === deck.length) { onEvent({ type: "memory_complete", game: "memory", timestamp: performance.timeOrigin + performance.now(), level }); if (level < 5) { onEvent({ type: "memory_level_up", game: "memory", timestamp: performance.timeOrigin + performance.now(), level: level + 1 }); setLevel((v) => v + 1) } } } setFlipped([]) }, 550) } }
  const restart = () => { setDeck([...Array.from({ length: pairs }, (_, i) => SHAPES[i]), ...Array.from({ length: pairs }, (_, i) => SHAPES[i])].sort(() => Math.random() - 0.5)); setMatched([]); setFlipped([]); setReady(false); setPreview(3); onEvent({ type: "memory_preview", game: "memory", timestamp: performance.timeOrigin + performance.now(), level }) }
  return <section className="game-card" id="panel-memory" role="tabpanel"><div className="game-heading"><div><p className="eyebrow">COGNITIVE / LEVEL {level}</p><h2>Memory Training</h2><p>Ingat posisi bentuk yang sama. Level berikutnya bertambah sulit.</p></div><button className="secondary-button" onClick={restart}>Mulai Ulang</button></div><div className="memory-status" aria-live="polite">{!ready ? preview > 0 ? `Hafalkan kartu: ${preview}` : <button className="ready-button" onClick={() => { setReady(true); onEvent({ type: "memory_preview", game: "memory", timestamp: performance.timeOrigin + performance.now(), level }) }}>Saya Siap</button> : `${matched.length / 2} dari ${pairs} pasangan cocok`}</div><div className="memory-grid" style={{ gridTemplateColumns: `repeat(${cols}, minmax(0, 1fr))` }}>{deck.map((shape, i) => <button key={i} className={`memory-card ${flipped.includes(i) || matched.includes(i) ? "revealed" : ""}`} onClick={() => choose(i)} aria-label={`Kartu ${i + 1}`}><span>{flipped.includes(i) || matched.includes(i) ? shape : "?"}</span></button>)}</div></section>
}
